[package]
name = "margined_utils"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
description = "Common helpers for margin protocol contracts"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw-controllers = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
margined_common = { workspace = true }
margined_perp = { workspace = true }
cw20 = { workspace = true }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw20-base = { workspace = true, features = ["library"] }
cw-multi-test = { workspace = true }
osmosis-test-tube = { workspace = true }
test-tube = { workspace = true }
